name: Hatch workflow
on:
  push:
    paths:
      - 'hatch-demo/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Lint
        run: hatch run dev:check
      - name: Run tests
        run: hatch run dev:test