name: Poetry workflow
on:
  push:
    paths:
      - 'poetry-demo/**'
      - '.github/workflows/poetry.yml'
defaults:
  run:
    working-directory: ./poetry-demo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install deps
        run: poetry install
      - name: Lint
        run: poetry run ruff check
      - name: Run tests
        run: poetry run pytest