name: uv workflow
on:
  push:
    paths:
      - 'uv-demo/**'
      - '.github/workflows/uv.yml'
defaults:
  run:
    working-directory: ./uv-demo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv 0.4.2
        run: curl -LsSf https://astral.sh/uv/0.4.2/install.sh | sh
      - name: Sync
        run: uv sync --all-extras --dev
      - name: Lint
        run: uv run ruff check
      - name: Run tests
        run: uv run pytest